# Generated by Django 5.1 on 2024-11-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('CategoryImage', models.ImageField(blank=True, null=True, upload_to='CategoryImages')),
                ('Description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
