# Generated by Django 5.1 on 2024-11-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='CategoryImages')),
                ('ProductDescription', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
