# Generated by Django 5.1 on 2024-11-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0002_shopproductdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
