# Generated by Django 5.1 on 2024-11-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0003_shopproductdb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductdb',
            name='Category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
