# Generated by Django 5.1 on 2024-11-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0004_shopproductdb_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Objective', models.CharField(blank=True, max_length=100, null=True)),
                ('Diet', models.CharField(blank=True, max_length=100, null=True)),
                ('BreakFast', models.CharField(blank=True, max_length=100, null=True)),
                ('BCalorie', models.IntegerField(blank=True, null=True)),
                ('BImage', models.ImageField(blank=True, null=True, upload_to='MealsImages')),
                ('Lunch', models.CharField(blank=True, max_length=100, null=True)),
                ('LCalorie', models.IntegerField(blank=True, null=True)),
                ('LImage', models.ImageField(blank=True, null=True, upload_to='MealsImages')),
                ('Dinner', models.CharField(blank=True, max_length=100, null=True)),
                ('DCalorie', models.IntegerField(blank=True, null=True)),
                ('DImage', models.ImageField(blank=True, null=True, upload_to='MealsImages')),
            ],
        ),
    ]
