# Generated by Django 5.1 on 2024-11-09 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0005_mealplans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealPlans',
            new_name='MealPlansDb',
        ),
    ]
