# Generated by Django 5.1.3 on 2024-11-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0006_rename_mealplans_mealplansdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.FileField(upload_to='video/%y')),
            ],
        ),
    ]
