# Generated by Django 5.1.3 on 2024-11-15 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0007_video'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video',
            new_name='videoDb',
        ),
    ]
