# Generated by Django 5.1.3 on 2024-11-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0008_rename_video_videodb'),
    ]

    operations = [
        migrations.AddField(
            model_name='videodb',
            name='EDescription',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='videodb',
            name='Objective1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videodb',
            name='calorie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
