# Generated by Django 5.1.3 on 2024-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0009_videodb_edescription_videodb_objective1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monday', models.TextField(blank=True, max_length=200, null=True)),
                ('Tuesday', models.TextField(blank=True, max_length=200, null=True)),
                ('Wednesday', models.TextField(blank=True, max_length=200, null=True)),
                ('Thursday', models.TextField(blank=True, max_length=200, null=True)),
                ('Friday', models.TextField(blank=True, max_length=200, null=True)),
                ('Saturday', models.TextField(blank=True, max_length=200, null=True)),
                ('Sunday', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='videodb',
            name='calorie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
