# Generated by Django 5.1.3 on 2024-11-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0010_workoutplans_alter_videodb_calorie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkoutPlans',
            new_name='WorkoutPlansDb',
        ),
    ]
