# Generated by Django 5.1.3 on 2024-11-16 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0012_workoutplansdb_fobjecective_workoutplansdb_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplansdb',
            old_name='FObjecective',
            new_name='FObjective',
        ),
    ]
