# Generated by Django 5.1 on 2024-12-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0013_rename_fobjecective_workoutplansdb_fobjective'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublishDate', models.DateField()),
                ('Heading', models.CharField(blank=True, max_length=100, null=True)),
                ('BlogDescription', models.CharField(blank=True, max_length=100, null=True)),
                ('Cover', models.ImageField(blank=True, null=True, upload_to='MealsImages')),
            ],
        ),
    ]
