# Generated by Django 5.1 on 2024-12-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0014_blogdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdb',
            name='intro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='blogdb',
            name='Cover',
            field=models.ImageField(blank=True, null=True, upload_to='BlogCovers'),
        ),
    ]
