# Generated by Django 5.1 on 2024-12-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthApp', '0015_blogdb_intro_alter_blogdb_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplansdb',
            name='Plan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
