# Generated by Django 5.1 on 2024-12-06 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_orderdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdb',
            old_name='TotalAmount',
            new_name='Total',
        ),
    ]
