# Generated by Django 5.1.3 on 2025-01-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_rename_totalamount_orderdb_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone_no', models.IntegerField(blank=True, null=True)),
                ('objective', models.CharField(blank=True, max_length=100, null=True)),
                ('Messages', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
