# Generated by Django 5.1.3 on 2025-01-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_contactdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdb',
            name='Messages',
        ),
        migrations.AddField(
            model_name='contactdb',
            name='Message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
