# Generated by Django 5.1.3 on 2025-03-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_remove_contactdb_messages_contactdb_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupdb',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
