# Generated by Django 5.1.3 on 2025-03-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_signupdb_height_signupdb_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupdb',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile'),
        ),
    ]
