# Generated by Django 5.1.3 on 2025-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_signupdb_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupdb',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
